ax_usb_driver-y += ax88179_178a.o
ax_usb_driver-y += ax88179a_772d.o
ax_usb_driver-y += ax_main.o
ax_usb_driver-$(CONFIG_ENABLE_AX88179_178A_PTP_FUNC) += ax_ptp.o
obj-$(CONFIG_USB_NET_AX88179_178A) += ax_usb_driver.o


